# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_creation_db/protos/request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from content_creation_db.protos import database_pb2 as content__creation__db_dot_protos_dot_database__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='content_creation_db/protos/request.proto',
  package='request',
  syntax='proto2',
  serialized_pb=_b('\n(content_creation_db/protos/request.proto\x12\x07request\x1a)content_creation_db/protos/database.proto\"*\n\x05Login\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"H\n\x06SignUp\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x1e\n\x0bLandingPage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12UserContentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"=\n\x15\x43reateQuestionRequest\x12$\n\x08question\x18\x01 \x01(\x0b\x32\x12.database.Question\"\x18\n\x16\x41rchiveQuestionRequest\"=\n\x15\x43reateResourceRequest\x12$\n\x08resource\x18\x01 \x01(\x0b\x32\x12.database.Resource\"C\n\x17\x43reateAssessmentRequest\x12(\n\nassessment\x18\x01 \x01(\x0b\x32\x14.database.Assessment\"4\n\x12\x43reateTopicRequest\x12\x1e\n\x05topic\x18\x01 \x01(\x0b\x32\x0f.database.Topic\"4\n\x12\x43reateThemeRequest\x12\x1e\n\x05theme\x18\x01 \x01(\x0b\x32\x0f.database.Theme\"\x16\n\x08GetTheme\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\tGetTopics\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x1d\n\x0eGetAssessments\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x1b\n\x0cGetQuestions\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x1a\n\x0bGetResource\x12\x0b\n\x03ids\x18\x01 \x03(\t')
  ,
  dependencies=[content__creation__db_dot_protos_dot_database__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='request.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='request.Login.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='request.Login.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=138,
)


_SIGNUP = _descriptor.Descriptor(
  name='SignUp',
  full_name='request.SignUp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='request.SignUp.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='request.SignUp.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='request.SignUp.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='request.SignUp.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=212,
)


_LANDINGPAGE = _descriptor.Descriptor(
  name='LandingPage',
  full_name='request.LandingPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='request.LandingPage.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=244,
)


_USERCONTENTREQUEST = _descriptor.Descriptor(
  name='UserContentRequest',
  full_name='request.UserContentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='request.UserContentRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=283,
)


_CREATEQUESTIONREQUEST = _descriptor.Descriptor(
  name='CreateQuestionRequest',
  full_name='request.CreateQuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='request.CreateQuestionRequest.question', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=346,
)


_ARCHIVEQUESTIONREQUEST = _descriptor.Descriptor(
  name='ArchiveQuestionRequest',
  full_name='request.ArchiveQuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=372,
)


_CREATERESOURCEREQUEST = _descriptor.Descriptor(
  name='CreateResourceRequest',
  full_name='request.CreateResourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource', full_name='request.CreateResourceRequest.resource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=435,
)


_CREATEASSESSMENTREQUEST = _descriptor.Descriptor(
  name='CreateAssessmentRequest',
  full_name='request.CreateAssessmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assessment', full_name='request.CreateAssessmentRequest.assessment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=504,
)


_CREATETOPICREQUEST = _descriptor.Descriptor(
  name='CreateTopicRequest',
  full_name='request.CreateTopicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='request.CreateTopicRequest.topic', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=558,
)


_CREATETHEMEREQUEST = _descriptor.Descriptor(
  name='CreateThemeRequest',
  full_name='request.CreateThemeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theme', full_name='request.CreateThemeRequest.theme', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=612,
)


_GETTHEME = _descriptor.Descriptor(
  name='GetTheme',
  full_name='request.GetTheme',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='request.GetTheme.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=636,
)


_GETTOPICS = _descriptor.Descriptor(
  name='GetTopics',
  full_name='request.GetTopics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='request.GetTopics.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=662,
)


_GETASSESSMENTS = _descriptor.Descriptor(
  name='GetAssessments',
  full_name='request.GetAssessments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='request.GetAssessments.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=693,
)


_GETQUESTIONS = _descriptor.Descriptor(
  name='GetQuestions',
  full_name='request.GetQuestions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='request.GetQuestions.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=722,
)


_GETRESOURCE = _descriptor.Descriptor(
  name='GetResource',
  full_name='request.GetResource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='request.GetResource.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=750,
)

_CREATEQUESTIONREQUEST.fields_by_name['question'].message_type = content__creation__db_dot_protos_dot_database__pb2._QUESTION
_CREATERESOURCEREQUEST.fields_by_name['resource'].message_type = content__creation__db_dot_protos_dot_database__pb2._RESOURCE
_CREATEASSESSMENTREQUEST.fields_by_name['assessment'].message_type = content__creation__db_dot_protos_dot_database__pb2._ASSESSMENT
_CREATETOPICREQUEST.fields_by_name['topic'].message_type = content__creation__db_dot_protos_dot_database__pb2._TOPIC
_CREATETHEMEREQUEST.fields_by_name['theme'].message_type = content__creation__db_dot_protos_dot_database__pb2._THEME
DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['SignUp'] = _SIGNUP
DESCRIPTOR.message_types_by_name['LandingPage'] = _LANDINGPAGE
DESCRIPTOR.message_types_by_name['UserContentRequest'] = _USERCONTENTREQUEST
DESCRIPTOR.message_types_by_name['CreateQuestionRequest'] = _CREATEQUESTIONREQUEST
DESCRIPTOR.message_types_by_name['ArchiveQuestionRequest'] = _ARCHIVEQUESTIONREQUEST
DESCRIPTOR.message_types_by_name['CreateResourceRequest'] = _CREATERESOURCEREQUEST
DESCRIPTOR.message_types_by_name['CreateAssessmentRequest'] = _CREATEASSESSMENTREQUEST
DESCRIPTOR.message_types_by_name['CreateTopicRequest'] = _CREATETOPICREQUEST
DESCRIPTOR.message_types_by_name['CreateThemeRequest'] = _CREATETHEMEREQUEST
DESCRIPTOR.message_types_by_name['GetTheme'] = _GETTHEME
DESCRIPTOR.message_types_by_name['GetTopics'] = _GETTOPICS
DESCRIPTOR.message_types_by_name['GetAssessments'] = _GETASSESSMENTS
DESCRIPTOR.message_types_by_name['GetQuestions'] = _GETQUESTIONS
DESCRIPTOR.message_types_by_name['GetResource'] = _GETRESOURCE

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.Login)
  ))
_sym_db.RegisterMessage(Login)

SignUp = _reflection.GeneratedProtocolMessageType('SignUp', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUP,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.SignUp)
  ))
_sym_db.RegisterMessage(SignUp)

LandingPage = _reflection.GeneratedProtocolMessageType('LandingPage', (_message.Message,), dict(
  DESCRIPTOR = _LANDINGPAGE,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.LandingPage)
  ))
_sym_db.RegisterMessage(LandingPage)

UserContentRequest = _reflection.GeneratedProtocolMessageType('UserContentRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERCONTENTREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.UserContentRequest)
  ))
_sym_db.RegisterMessage(UserContentRequest)

CreateQuestionRequest = _reflection.GeneratedProtocolMessageType('CreateQuestionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEQUESTIONREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.CreateQuestionRequest)
  ))
_sym_db.RegisterMessage(CreateQuestionRequest)

ArchiveQuestionRequest = _reflection.GeneratedProtocolMessageType('ArchiveQuestionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ARCHIVEQUESTIONREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.ArchiveQuestionRequest)
  ))
_sym_db.RegisterMessage(ArchiveQuestionRequest)

CreateResourceRequest = _reflection.GeneratedProtocolMessageType('CreateResourceRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATERESOURCEREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.CreateResourceRequest)
  ))
_sym_db.RegisterMessage(CreateResourceRequest)

CreateAssessmentRequest = _reflection.GeneratedProtocolMessageType('CreateAssessmentRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEASSESSMENTREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.CreateAssessmentRequest)
  ))
_sym_db.RegisterMessage(CreateAssessmentRequest)

CreateTopicRequest = _reflection.GeneratedProtocolMessageType('CreateTopicRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETOPICREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.CreateTopicRequest)
  ))
_sym_db.RegisterMessage(CreateTopicRequest)

CreateThemeRequest = _reflection.GeneratedProtocolMessageType('CreateThemeRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETHEMEREQUEST,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.CreateThemeRequest)
  ))
_sym_db.RegisterMessage(CreateThemeRequest)

GetTheme = _reflection.GeneratedProtocolMessageType('GetTheme', (_message.Message,), dict(
  DESCRIPTOR = _GETTHEME,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.GetTheme)
  ))
_sym_db.RegisterMessage(GetTheme)

GetTopics = _reflection.GeneratedProtocolMessageType('GetTopics', (_message.Message,), dict(
  DESCRIPTOR = _GETTOPICS,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.GetTopics)
  ))
_sym_db.RegisterMessage(GetTopics)

GetAssessments = _reflection.GeneratedProtocolMessageType('GetAssessments', (_message.Message,), dict(
  DESCRIPTOR = _GETASSESSMENTS,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.GetAssessments)
  ))
_sym_db.RegisterMessage(GetAssessments)

GetQuestions = _reflection.GeneratedProtocolMessageType('GetQuestions', (_message.Message,), dict(
  DESCRIPTOR = _GETQUESTIONS,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.GetQuestions)
  ))
_sym_db.RegisterMessage(GetQuestions)

GetResource = _reflection.GeneratedProtocolMessageType('GetResource', (_message.Message,), dict(
  DESCRIPTOR = _GETRESOURCE,
  __module__ = 'content_creation_db.protos.request_pb2'
  # @@protoc_insertion_point(class_scope:request.GetResource)
  ))
_sym_db.RegisterMessage(GetResource)


# @@protoc_insertion_point(module_scope)
