# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_creation_db/protos/response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from content_creation_db.protos import database_pb2 as content__creation__db_dot_protos_dot_database__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='content_creation_db/protos/response.proto',
  package='response',
  syntax='proto2',
  serialized_pb=_b('\n)content_creation_db/protos/response.proto\x12\x08response\x1a)content_creation_db/protos/database.proto\"T\n\x0f\x41\x63knowledgement\x12\x1f\n\x17is_successful_execution\x18\x01 \x01(\x08\x12 \n\x18\x65xecution_error_messages\x18\x02 \x03(\t\"J\n\x05Login\x12\x1f\n\x17is_successful_execution\x18\x01 \x01(\x08\x12 \n\x18\x65xecution_error_messages\x18\x02 \x03(\t\"\x82\x01\n\x13UserContentResponse\x12\x1f\n\x06themes\x18\x01 \x03(\x0b\x32\x0f.database.Theme\x12\x1f\n\x06topics\x18\x02 \x03(\x0b\x32\x0f.database.Topic\x12)\n\x0b\x61ssessments\x18\x03 \x03(\x0b\x32\x14.database.Assessment\"\x81\x01\n\x12\x41llContentResponse\x12\x1f\n\x06themes\x18\x01 \x03(\x0b\x32\x0f.database.Theme\x12\x1f\n\x06topics\x18\x02 \x03(\x0b\x32\x0f.database.Topic\x12)\n\x0b\x61ssessments\x18\x03 \x03(\x0b\x32\x14.database.Assessment')
  ,
  dependencies=[content__creation__db_dot_protos_dot_database__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACKNOWLEDGEMENT = _descriptor.Descriptor(
  name='Acknowledgement',
  full_name='response.Acknowledgement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_successful_execution', full_name='response.Acknowledgement.is_successful_execution', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='execution_error_messages', full_name='response.Acknowledgement.execution_error_messages', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=182,
)


_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='response.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_successful_execution', full_name='response.Login.is_successful_execution', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='execution_error_messages', full_name='response.Login.execution_error_messages', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=258,
)


_USERCONTENTRESPONSE = _descriptor.Descriptor(
  name='UserContentResponse',
  full_name='response.UserContentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='themes', full_name='response.UserContentResponse.themes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='response.UserContentResponse.topics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assessments', full_name='response.UserContentResponse.assessments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=391,
)


_ALLCONTENTRESPONSE = _descriptor.Descriptor(
  name='AllContentResponse',
  full_name='response.AllContentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='themes', full_name='response.AllContentResponse.themes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='response.AllContentResponse.topics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assessments', full_name='response.AllContentResponse.assessments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=523,
)

_USERCONTENTRESPONSE.fields_by_name['themes'].message_type = content__creation__db_dot_protos_dot_database__pb2._THEME
_USERCONTENTRESPONSE.fields_by_name['topics'].message_type = content__creation__db_dot_protos_dot_database__pb2._TOPIC
_USERCONTENTRESPONSE.fields_by_name['assessments'].message_type = content__creation__db_dot_protos_dot_database__pb2._ASSESSMENT
_ALLCONTENTRESPONSE.fields_by_name['themes'].message_type = content__creation__db_dot_protos_dot_database__pb2._THEME
_ALLCONTENTRESPONSE.fields_by_name['topics'].message_type = content__creation__db_dot_protos_dot_database__pb2._TOPIC
_ALLCONTENTRESPONSE.fields_by_name['assessments'].message_type = content__creation__db_dot_protos_dot_database__pb2._ASSESSMENT
DESCRIPTOR.message_types_by_name['Acknowledgement'] = _ACKNOWLEDGEMENT
DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['UserContentResponse'] = _USERCONTENTRESPONSE
DESCRIPTOR.message_types_by_name['AllContentResponse'] = _ALLCONTENTRESPONSE

Acknowledgement = _reflection.GeneratedProtocolMessageType('Acknowledgement', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGEMENT,
  __module__ = 'content_creation_db.protos.response_pb2'
  # @@protoc_insertion_point(class_scope:response.Acknowledgement)
  ))
_sym_db.RegisterMessage(Acknowledgement)

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN,
  __module__ = 'content_creation_db.protos.response_pb2'
  # @@protoc_insertion_point(class_scope:response.Login)
  ))
_sym_db.RegisterMessage(Login)

UserContentResponse = _reflection.GeneratedProtocolMessageType('UserContentResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERCONTENTRESPONSE,
  __module__ = 'content_creation_db.protos.response_pb2'
  # @@protoc_insertion_point(class_scope:response.UserContentResponse)
  ))
_sym_db.RegisterMessage(UserContentResponse)

AllContentResponse = _reflection.GeneratedProtocolMessageType('AllContentResponse', (_message.Message,), dict(
  DESCRIPTOR = _ALLCONTENTRESPONSE,
  __module__ = 'content_creation_db.protos.response_pb2'
  # @@protoc_insertion_point(class_scope:response.AllContentResponse)
  ))
_sym_db.RegisterMessage(AllContentResponse)


# @@protoc_insertion_point(module_scope)
